function rustIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function rustType(type) {
  if (!type) return 'serde_json::Value';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `std::collections::BTreeSet<${rustType(type.item)}>`;
    if (type.kind === 'list') return `Vec<${rustType(type.item)}>`;
    if (type.kind === 'map') return `std::collections::BTreeMap<${rustType(type.key)}, ${rustType(type.value)}>`;
    if (type.kind === 'ref') return rustIdentifier(type.name);
    return 'serde_json::Value';
  }
  const primitive = { Text: 'String', String: 'String', Bool: 'bool', Boolean: 'bool', Int: 'i64', Float: 'f64', Number: 'f64', Instant: 'String', Json: 'serde_json::Value', Patch: 'Vec<FrontierPatchOperation>' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `std::collections::BTreeSet<${rustType(set[1].trim())}>`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `Vec<${rustType(list[1].trim())}>`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `std::collections::BTreeMap<${rustType(map[1].trim())}, ${rustType(map[2].trim())}>`;
  return rustIdentifier(type);
}

export function emitRust(document, options = {}) {
  const lines = [];
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-rust.';
  lines.push(`// ${banner}`, '', '#[derive(Clone, Debug, PartialEq)]', 'pub enum FrontierPatchOperation {', '    Set { path: String, value: serde_json::Value },', '    Remove { path: String },', '    Insert { path: String, value: serde_json::Value },', '    Merge { path: String, value: serde_json::Value },', '}', '');
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.type) lines.push(`pub type ${rustIdentifier(node.name)} = ${rustType(node.type)};`, '');
    if (node.kind === 'type' && node.fields?.length) emitStruct(lines, node.name, node.fields);
    if (node.kind === 'entity') emitStruct(lines, node.name, node.fields);
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') lines.push(`pub fn ${rustIdentifier(node.name)}(_state: &serde_json::Value, _input: ${rustType(node.input)}) -> ${rustType(node.returns ?? 'Patch')} {`, '    Vec::new()', '}', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitStruct(lines, name, fields) {
  lines.push('#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]', `pub struct ${rustIdentifier(name)} {`);
  for (const field of fields) lines.push(`    pub ${rustIdentifier(field.name)}: ${rustType(field.type)},`);
  lines.push('}', '');
}
