function rustIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function rustConstIdentifier(name) {
  return rustIdentifier(name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function rustString(value) {
  return JSON.stringify(String(value ?? ''));
}

function rustType(type) {
  if (!type) return 'serde_json::Value';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `std::collections::BTreeSet<${rustType(type.item)}>`;
    if (type.kind === 'list') return `Vec<${rustType(type.item)}>`;
    if (type.kind === 'map') return `std::collections::BTreeMap<${rustType(type.key)}, ${rustType(type.value)}>`;
    if (type.kind === 'ref') return rustIdentifier(type.name);
    return 'serde_json::Value';
  }
  const primitive = { Text: 'String', String: 'String', Bool: 'bool', Boolean: 'bool', Int: 'i64', Float: 'f64', Number: 'f64', Instant: 'String', Json: 'serde_json::Value', Patch: 'Vec<FrontierPatchOperation>' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `std::collections::BTreeSet<${rustType(set[1].trim())}>`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `Vec<${rustType(list[1].trim())}>`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `std::collections::BTreeMap<${rustType(map[1].trim())}, ${rustType(map[2].trim())}>`;
  return rustIdentifier(type);
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toRustAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-rust.';
  const items = [{ kind: 'patchEnum', name: 'FrontierPatchOperation' }];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.type) items.push({ kind: 'typeAlias', name: rustIdentifier(node.name), type: rustType(node.type), sourceRef: sourceRef(node) });
    if (node.kind === 'type' && node.fields?.length) items.push(structItem(node, node.fields));
    if (node.kind === 'entity') items.push(structItem(node, node.fields));
    if (node.kind === 'capability') items.push({
      kind: 'capabilityDescriptor',
      name: rustConstIdentifier(node.name),
      capability: node.capability,
      adapters: (node.adapters ?? []).map((adapter) => ({
        language: adapter.target?.language ?? '',
        platform: adapter.target?.platform ?? '',
        symbol: adapter.symbol ?? ''
      })),
      sourceRef: sourceRef(node)
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') items.push({ kind: 'function', name: rustIdentifier(node.name), inputType: rustType(node.input), returnType: rustType(node.returns ?? 'Patch'), sourceRef: sourceRef(node) });
  }
  return { kind: 'rust.module', banner, items };
}

export function renderRustAst(ast) {
  return renderRustAstWithSourceMap(ast).code;
}

export function renderRustAstWithSourceMap(ast, options = {}) {
  const lines = [];
  const mappings = [];
  const target = normalizeTarget(options, 'rust');
  lines.push(`// ${ast.banner}`, '');
  ast.items.forEach((item, index) => {
    const startLine = lines.length + 1;
    const startIndex = lines.length;
    renderRustItem(lines, item);
    const generatedSpan = declarationBlockSpan(lines, startIndex, startLine, item, target, options.targetPath);
    if (item.sourceRef?.semanticNodeId && generatedSpan) {
      mappings.push(sourceMapMapping(item, index, generatedSpan, target, options, 'rust-renderer-declaration-block'));
    }
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return {
    code,
    sourceMap: sourceMapEnvelope(ast, mappings, target, options, 'rust', 'rust-renderer-declaration-block')
  };
}

function renderRustItem(lines, item) {
    if (item.kind === 'patchEnum') {
      lines.push('#[derive(Clone, Debug, PartialEq)]', `pub enum ${item.name} {`, '    Set { path: String, value: serde_json::Value },', '    Remove { path: String },', '    Insert { path: String, value: serde_json::Value },', '    Merge { path: String, value: serde_json::Value },', '}', '');
    }
    if (item.kind === 'typeAlias') lines.push(`pub type ${item.name} = ${item.type};`, '');
    if (item.kind === 'capabilityDescriptor') {
      lines.push(`pub const ${item.name}_CAPABILITY: &str = ${rustString(item.capability)};`);
      lines.push(`pub const ${item.name}_ADAPTERS: &[(&str, &str, &str)] = &[`);
      for (const adapter of item.adapters) lines.push(`    (${rustString(adapter.language)}, ${rustString(adapter.platform)}, ${rustString(adapter.symbol)}),`);
      lines.push('];', '');
    }
    if (item.kind === 'struct') {
      lines.push('#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]', `pub struct ${item.name} {`);
      for (const field of item.fields) lines.push(`    pub ${field.name}: ${field.type},`);
      lines.push('}', '');
    }
    if (item.kind === 'function') lines.push(`pub fn ${item.name}(_state: &serde_json::Value, _input: ${item.inputType}) -> ${item.returnType} {`, '    Vec::new()', '}', '');
}

export function emitRust(document, options = {}) {
  return renderRustAst(toRustAst(document, options));
}

export function emitRustWithSourceMap(document, options = {}) {
  const ast = toRustAst(document, options);
  const result = renderRustAstWithSourceMap(ast, {
    sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_rust`,
    ...options
  });
  return { ...result, ast };
}

function structItem(node, fields) {
  return {
    kind: 'struct',
    name: rustIdentifier(node.name),
    fields: fields.map((field) => ({ name: rustIdentifier(field.name), type: rustType(field.type) })),
    sourceRef: sourceRef(node, { regionIds: fields.map((field) => field.id) })
  };
}

function declarationBlockSpan(lines, startIndex, startLine, item, target, targetPath) {
  let endIndex = lines.length - 1;
  while (endIndex >= startIndex && lines[endIndex] === '') endIndex -= 1;
  if (endIndex < startIndex) return undefined;
  return definedObject({
    path: targetPath,
    target,
    targetPath,
    generatedName: item.name,
    startLine,
    startColumn: 1,
    endLine: endIndex + 1,
    endColumn: lines[endIndex].length + 1
  });
}

function normalizeTarget(options, language) {
  return definedObject({
    ...(options.target ?? {}),
    language: options.target?.language ?? language,
    emitPath: options.target?.emitPath ?? options.targetPath
  });
}

function sourceMapMapping(item, index, generatedSpan, target, options, strategy) {
  return definedObject({
    id: `map_${idFragment(item.sourceRef.semanticNodeId)}_${index}`,
    semanticNodeId: item.sourceRef.semanticNodeId,
    nativeSourceId: options.nativeSourceId,
    semanticSymbolId: options.semanticSymbolIdsBySemanticNodeId?.[item.sourceRef.semanticNodeId],
    semanticOccurrenceId: options.semanticOccurrenceIdsBySemanticNodeId?.[item.sourceRef.semanticNodeId],
    sourceSpan: options.sourceSpansBySemanticNodeId?.[item.sourceRef.semanticNodeId],
    generatedSpan,
    target,
    generatedName: item.name,
    evidenceIds: options.evidence?.map((record) => record.id),
    lossIds: options.lossIdsBySemanticNodeId?.[item.sourceRef.semanticNodeId],
    precision: 'declaration',
    metadata: {
      generatedSpanStrategy: strategy,
      sourceMapImplication: 'Generated span covers the emitted declaration block and is not token exact.',
      semanticIndexImplication: 'Mapping is anchored by semanticNodeId; symbol and occurrence ids are optional caller-provided links.',
      lossAccountingImplication: 'No loss ids are inferred by the printer; caller-provided loss ids are copied when available.',
      mergeReadinessImplication: 'Suitable for declaration-level overlap review, not fine-grained token merge admission.',
      semanticNodeKind: item.sourceRef.semanticNodeKind,
      semanticNodeName: item.sourceRef.semanticNodeName,
      regionIds: item.sourceRef.regionIds
    }
  });
}

function sourceMapEnvelope(ast, mappings, target, options, language, strategy) {
  return definedObject({
    kind: 'frontier.lang.sourceMap',
    version: 1,
    id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_${language}`,
    sourcePath: options.sourcePath,
    sourceHash: options.sourceHash,
    target,
    targetPath: options.targetPath,
    targetHash: options.targetHash,
    semanticIndexId: options.semanticIndexId,
    universalAstId: options.universalAstId,
    nativeAstId: options.nativeAstId,
    nativeSourceId: options.nativeSourceId,
    mappings,
    evidence: options.evidence ?? [],
    metadata: {
      generatedSpanStrategy: strategy,
      precision: 'declaration',
      sourceMapImplication: 'Approximate generated spans are emitted as sidecar mappings without rewriting the printer.',
      semanticIndexImplication: 'Semantic index linkage remains optional and can be attached through ids supplied in options.',
      lossAccountingImplication: 'The renderer does not create loss records; existing loss ids can be associated per semantic node.',
      mergeReadinessImplication: 'Declaration-block mappings can guide generated-output review but should not be treated as token-exact source maps.',
      ...(options.metadata ?? {})
    }
  });
}

function definedObject(object) {
  return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined));
}

function idFragment(value) {
  return rustIdentifier(String(value ?? 'unknown')).replace(/^_+/, '') || 'unknown';
}

export {
  createRustSemanticMergeEvidence,
  parseRustSemanticTree,
  queryRustItemRecords,
  summarizeRustSemanticTree
} from './source.js';
