function rustIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function rustConstIdentifier(name) {
  return rustIdentifier(name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function rustString(value) {
  return JSON.stringify(String(value ?? ''));
}

function rustType(type) {
  if (!type) return 'serde_json::Value';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `std::collections::BTreeSet<${rustType(type.item)}>`;
    if (type.kind === 'list') return `Vec<${rustType(type.item)}>`;
    if (type.kind === 'map') return `std::collections::BTreeMap<${rustType(type.key)}, ${rustType(type.value)}>`;
    if (type.kind === 'ref') return rustIdentifier(type.name);
    return 'serde_json::Value';
  }
  const primitive = { Text: 'String', String: 'String', Bool: 'bool', Boolean: 'bool', Int: 'i64', Float: 'f64', Number: 'f64', Instant: 'String', Json: 'serde_json::Value', Patch: 'Vec<FrontierPatchOperation>' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `std::collections::BTreeSet<${rustType(set[1].trim())}>`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `Vec<${rustType(list[1].trim())}>`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `std::collections::BTreeMap<${rustType(map[1].trim())}, ${rustType(map[2].trim())}>`;
  return rustIdentifier(type);
}

export function toRustAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-rust.';
  const items = [{ kind: 'patchEnum', name: 'FrontierPatchOperation' }];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.type) items.push({ kind: 'typeAlias', name: rustIdentifier(node.name), type: rustType(node.type) });
    if (node.kind === 'type' && node.fields?.length) items.push(structItem(node.name, node.fields));
    if (node.kind === 'entity') items.push(structItem(node.name, node.fields));
    if (node.kind === 'capability') items.push({
      kind: 'capabilityDescriptor',
      name: rustConstIdentifier(node.name),
      capability: node.capability,
      adapters: (node.adapters ?? []).map((adapter) => ({
        language: adapter.target?.language ?? '',
        platform: adapter.target?.platform ?? '',
        symbol: adapter.symbol ?? ''
      }))
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') items.push({ kind: 'function', name: rustIdentifier(node.name), inputType: rustType(node.input), returnType: rustType(node.returns ?? 'Patch') });
  }
  return { kind: 'rust.module', banner, items };
}

export function renderRustAst(ast) {
  const lines = [];
  lines.push(`// ${ast.banner}`, '');
  for (const item of ast.items) {
    if (item.kind === 'patchEnum') {
      lines.push('#[derive(Clone, Debug, PartialEq)]', `pub enum ${item.name} {`, '    Set { path: String, value: serde_json::Value },', '    Remove { path: String },', '    Insert { path: String, value: serde_json::Value },', '    Merge { path: String, value: serde_json::Value },', '}', '');
    }
    if (item.kind === 'typeAlias') lines.push(`pub type ${item.name} = ${item.type};`, '');
    if (item.kind === 'capabilityDescriptor') {
      lines.push(`pub const ${item.name}_CAPABILITY: &str = ${rustString(item.capability)};`);
      lines.push(`pub const ${item.name}_ADAPTERS: &[(&str, &str, &str)] = &[`);
      for (const adapter of item.adapters) lines.push(`    (${rustString(adapter.language)}, ${rustString(adapter.platform)}, ${rustString(adapter.symbol)}),`);
      lines.push('];', '');
    }
    if (item.kind === 'struct') {
      lines.push('#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]', `pub struct ${item.name} {`);
      for (const field of item.fields) lines.push(`    pub ${field.name}: ${field.type},`);
      lines.push('}', '');
    }
    if (item.kind === 'function') lines.push(`pub fn ${item.name}(_state: &serde_json::Value, _input: ${item.inputType}) -> ${item.returnType} {`, '    Vec::new()', '}', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function emitRust(document, options = {}) {
  return renderRustAst(toRustAst(document, options));
}

function structItem(name, fields) {
  return { kind: 'struct', name: rustIdentifier(name), fields: fields.map((field) => ({ name: rustIdentifier(field.name), type: rustType(field.type) })) };
}
